version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: mulungu
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
  mulungu:
    build: .
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: mulungu
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
    - "8080:8080"
    command: go run main.go
    depends_on:
      - db
    links:
      - db
    