version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mulungu
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
  mulungu:
    build: .
    ports:
    - "8080:8080"
    command: >
      sh -c "ls -la &&
             chmod +x $GOPATH/src/github.com/cauli/mulungu/wait-for &&
             $GOPATH/src/github.com/cauli/mulungu/wait-for db:5432 -- go run main.go"
    depends_on:
      - db
    links:
      - db
